# Generated by Django 6.0.6 on 2026-06-23 20:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryFamily',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_familia', models.CharField(max_length=100)),
                ('responsavel_nome', models.CharField(max_length=255)),
                ('cpf_nis', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_membros', models.IntegerField(default=1)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('data_ultima_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('lgpd_accept', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'familias',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(default='554732073009', max_length=20)),
                ('cep_instituicao', models.CharField(default='89205-000', max_length=10)),
                ('endereco_instituicao', models.CharField(default='Rua Aubé, 895 – Boa Vista, Joinville/SC', max_length=255)),
                ('pix_key', models.CharField(default='joinville@ondadura.com', max_length=255)),
                ('qr_code_image', models.TextField(blank=True)),
                ('cnpj', models.CharField(default='22788440000198', max_length=20)),
                ('email_contato', models.CharField(default='contato@ondadura.com', max_length=255)),
                ('instagram_link', models.CharField(default='https://www.instagram.com/ondadura/', max_length=255)),
            ],
            options={
                'db_table': 'global_configuration',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(default='doador', max_length=50)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_atividades',
            },
        ),
        migrations.CreateModel(
            name='DonationIntake',
            fields=[
                ('id_doacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_doador', models.CharField(max_length=255)),
                ('telefone_doador', models.CharField(max_length=20)),
                ('status_doacao', models.CharField(default='pendente', max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('codigo_rastreamento', models.CharField(max_length=20, unique=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doacoes_entradas',
            },
        ),
        migrations.CreateModel(
            name='OutboundDelivery',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('id_familia', models.ForeignKey(db_column='id_familia', on_delete=django.db.models.deletion.RESTRICT, to='core.beneficiaryfamily')),
                ('id_usuario_operador', models.ForeignKey(db_column='id_usuario_operador', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entregas_saidas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('meta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.category')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id_doacao_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item_personalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_doacao', models.ForeignKey(db_column='id_doacao', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.donationintake')),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'db_table': 'doacoes_itens',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id_entrega_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_cota_utilizada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_entrega', models.ForeignKey(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.outbounddelivery')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
            options={
                'db_table': 'entregas_itens',
            },
        ),
    ]
